services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: d03a89f3
            MARIADB_USER: d03a89f3
            MARIADB_PASSWORD: password
